export const metadata = { title: 'Legal & privacy' }

export default function LegalPage() {
  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-2xl font-bold">Legal & privacy</h1>

      <h2 className="mt-8 text-lg font-semibold">What this is</h2>
      <p className="mt-2 text-neutral-700">
        Overprint is a non-commercial student demonstration, built for a course. Nothing here is
        actually for sale — no goods are shipped, and every payment runs through Stripe in test
        mode, so no real money can change hands. Please do not enter real card details or a real
        address.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Who runs it</h2>
      <p className="mt-2 text-neutral-700">
        Overprint — a student project by Peter. Contact:{' '}
        <a href="mailto:overprintdemoshop@gmail.com" className="underline">
          overprintdemoshop@gmail.com
        </a>
        . No postal address is published here: our understanding is that the German
        address-disclosure duty (§5 DDG) attaches to services run on a sustained, organised
        (<em>geschäftsmäßig</em>) basis, not a one-off non-commercial demonstration like this one.
        Email is the way to reach us.
      </p>

      <h2 className="mt-8 text-lg font-semibold">AI-generated images</h2>
      <p className="mt-2 text-neutral-700">
        Product images in this shop are AI-generated rather than photographed. Each image&apos;s
        record states how it was made, and any image generated by AI is labelled as such on its
        product page. Where an image is AI-generated, it also carries C2PA provenance metadata
        identifying the generator that made it.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Privacy</h2>
      <p className="mt-2 text-neutral-700">
        We collect your email, name, shipping address, order contents, and the Stripe identifiers
        for your payment (a checkout session id and a payment intent id), plus a record of your
        consent to these terms: a checkbox on the product page, linking back to this page, checked
        again on our server before checkout can start, and timestamped onto your order. Card
        details themselves go straight to Stripe — we never see or store them.
      </p>
      <p className="mt-2 text-neutral-700">
        Our lawful basis is not the same for every item. Your email, name, shipping address, order
        contents and the Stripe identifiers are held to perform the contract of sale (Art. 6(1)(b)
        GDPR). The consent timestamp is held under our legitimate interest in being able to show
        that the terms were accepted before an order was placed (Art. 6(1)(f)) — it is a record
        that consent was given, not data we hold on the strength of that consent. Vercel and
        Supabase process all of it as our processors, acting only on our instructions. Stripe
        processes payment data as an independent controller, and performs its own fraud screening
        on it under its own legitimate interests — it decides its own purposes and means for that
        data, so it answers for it on its own terms, not ours.
      </p>
      <p className="mt-2 text-neutral-700">
        Data is stored in AWS eu-west-1, with serverless functions pinned to the dub1 region. Our
        retention targets: unpaid orders are removed after 30 days, and paid orders are kept for 2
        years, after which they are redacted — their identity details (email, name, address)
        cleared, leaving only the amount and date as a commercial record. Enforcement is manual and
        operator-initiated: an operator runs a maintenance script by hand to apply these limits.
        Nothing is purged or redacted automatically, and no recurring schedule does this for them.
      </p>
      <p className="mt-2 text-neutral-700">
        To exercise your rights of access, rectification, erasure, or portability, email the
        address above. None of these is self-service or automated: an operator with database
        access acts on your request by hand. Access, portability and erasure each have a
        maintenance script the operator runs. Rectification has none — the fields holding your
        name, email and address are deliberately locked against editing from the admin panel and
        the API, so a correction is made by the operator directly against the database. We cannot
        erase data held by Stripe: it is an independent controller with its own retention
        obligations, so you will need to contact Stripe directly for that.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Not legal advice</h2>
      <p className="mt-2 text-neutral-700">
        This page is a student project&apos;s good-faith attempt at a privacy notice, not a
        professionally drafted policy or legal advice.
      </p>
    </main>
  )
}
