export const metadata = { title: 'Legal & privacy' }

export default function LegalPage() {
  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-2xl font-bold">Legal & privacy</h1>

      <h2 className="mt-8 text-lg font-semibold">What this is</h2>
      <p className="mt-2 text-neutral-700">
        Overprint is a non-commercial student demonstration, built for a course. Nothing here is
        actually for sale — no goods are shipped, and every payment runs through Stripe in test
        mode, so no real money can change hands. Please do not enter real card details or a real
        address.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Who runs it</h2>
      <p className="mt-2 text-neutral-700">
        Overprint — a student project by Peter. Contact:{' '}
        <a href="mailto:overprintdemoshop@gmail.com" className="underline">
          overprintdemoshop@gmail.com
        </a>
        . No postal address is published here: the German address-disclosure duty (§5 DDG)
        attaches to commercial services, and this is not one. Email is the way to reach us.
      </p>

      <h2 className="mt-8 text-lg font-semibold">AI-generated images</h2>
      <p className="mt-2 text-neutral-700">
        Every product image is generated by an AI image model, not photographed. Each one carries
        C2PA provenance metadata identifying the generator that made it.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Privacy</h2>
      <p className="mt-2 text-neutral-700">
        We collect your email, name, shipping address, and order contents, plus a record of your
        consent to these terms: a checkbox on the product page, linking back to this page, checked
        again on our server before checkout can start, and timestamped onto your order. Card
        details go straight to Stripe — we never see or store them.
      </p>
      <p className="mt-2 text-neutral-700">
        We keep the order record to perform the contract of sale, and use it for fraud prevention
        under our legitimate interests. Vercel and Supabase process this data as our processors,
        acting only on our instructions. Stripe processes payment data as an independent
        controller — it decides its own purposes and means for that data, so it answers for it on
        its own terms, not ours.
      </p>
      <p className="mt-2 text-neutral-700">
        Data is stored in AWS eu-west-1, with serverless functions pinned to the dub1 region.
        Unpaid orders are deleted after 30 days; paid orders are kept for 2 years, then redacted.
      </p>
      <p className="mt-2 text-neutral-700">
        To access, correct, delete, or receive a copy of your data, email the address above. We
        cannot erase data held by Stripe: it is an independent controller with its own retention
        obligations, so you will need to contact Stripe directly for that.
      </p>

      <h2 className="mt-8 text-lg font-semibold">Not legal advice</h2>
      <p className="mt-2 text-neutral-700">
        This page is a student project&apos;s good-faith attempt at a privacy notice, not a
        professionally drafted policy or legal advice.
      </p>
    </main>
  )
}
